Write-Host "Hello from PowerShell DevOps demo"

$demoMessage = "Pipeline script executed successfully"

Write-Host "DemoMessage: $demoMessage"

New-Item -ItemType Directory -Force -Path "output" | Out-Null

"Generated by demo.ps1" | Out-File -FilePath "output/demo-powershell.txt"

Write-Host "Output file created successfully"

exit 0
